-- Oracle Database Schema for User Authentication System
-- Run this script in your Oracle database to create the required tables

-- Drop tables if they exist (for clean reinstall)
-- DROP TABLE user_activity CASCADE CONSTRAINTS;
-- DROP TABLE user_sessions CASCADE CONSTRAINTS;
-- DROP TABLE users CASCADE CONSTRAINTS;

-- Create users table
CREATE TABLE USERS (
    ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    google_id VARCHAR2(100) UNIQUE NOT NULL,
    email VARCHAR2(255) UNIQUE NOT NULL,
    NAME VARCHAR2(500) NOT NULL,
    profile_picture VARCHAR2(1000),
    is_active NUMBER(1) DEFAULT 1 CHECK (is_active IN (0,1)),
    is_admin NUMBER(1) DEFAULT 0 CHECK (is_admin IN (0,1)),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_login TIMESTAMP,
    login_count NUMBER DEFAULT 0,
    user_info CLOB, -- JSON field for additional user data
    
    -- Trading platform configuration
    trading_user_id VARCHAR2(100),
    kite_api_key VARCHAR2(100),
    kite_access_token VARCHAR2(500),
    data_access_level NUMBER DEFAULT 1,
    allowed_features VARCHAR2(1000) DEFAULT 'dashboard,holdings,gtt',
    timezone VARCHAR2(50) DEFAULT 'Asia/Kolkata',
    
    -- Access control
    ip_whitelist CLOB,
    session_timeout NUMBER DEFAULT 3600,
    max_concurrent_sessions NUMBER DEFAULT 2
);

-- Create sessions table for better session management
CREATE TABLE user_sessions (
    ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    session_token VARCHAR2(500) UNIQUE NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMP,
    ip_address VARCHAR2(45),
    user_agent VARCHAR2(1000),
    is_active NUMBER(1) DEFAULT 1 CHECK (is_active IN (0,1)),
    CONSTRAINT fk_user_sessions_user_id FOREIGN KEY (user_id) REFERENCES USERS (ID)
);

-- Create user activity log
CREATE TABLE user_activity (
    ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    ACTION VARCHAR2(255) NOT NULL,
    resources VARCHAR2(500),
    ip_address VARCHAR2(45),
    TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    SUCCESS NUMBER(1) DEFAULT 1 CHECK (SUCCESS IN (0,1)),
    details CLOB,
    CONSTRAINT fk_user_activity_user_id FOREIGN KEY (user_id) REFERENCES USERS (ID)
);

-- Create indexes for better performance
--CREATE INDEX idx_users_google_id ON USERS(google_id);
--CREATE INDEX idx_users_email ON USERS(email);
--CREATE INDEX idx_user_sessions_token ON user_sessions(session_token);
CREATE INDEX idx_user_sessions_user_id ON user_sessions(user_id);
CREATE INDEX idx_user_activity_user_id ON user_activity(user_id);
CREATE INDEX idx_user_activity_timestamp ON user_activity(TIMESTAMP);

-- Create sequences (if needed for older Oracle versions)
-- CREATE SEQUENCE users_seq START WITH 1 INCREMENT BY 1;
-- CREATE SEQUENCE user_sessions_seq START WITH 1 INCREMENT BY 1;
-- CREATE SEQUENCE user_activity_seq START WITH 1 INCREMENT BY 1;

COMMIT;
